### ISSUE TITLE
Build an UI tool replicating the Entity Details View

### ISSUE THREAD

**Issue by abhilash-m96** [rasoolbasha048022/UI-Learning-#1]
[Entity Details View](https://nference.kwikui.com/view/ec2245)

Build a replica of the above tool without using `nunjucks` templating. Use only javascript and its other libraries.

**Comment by rasoolbasha048022** [comment]
I completed the first table and working on the model box inside a datatable.

**Comment by rasoolbasha048022** [comment]
Model inside the datatable not getting the uniques rows data.I'm trying to fixing this issue

**Comment by rasoolbasha048022** [comment]
Task is Completed

**Comment by rasoolbasha048022** [comment]
Below is the link for Bulid an UI Tool replicating the Entity Details View

https://kwikui.com/view/7e5dcb#view

**Comment by abhilash-m96** [comment]
@rasoolbasha048022  Can you raise a PR for the same.

**Comment by abhilash-m96** [comment]
@rasoolbasha048022 
1. I don't see `akas` data for some records, even though there's data from the backend response.

**refer below:** record *81453*
![image](https://user-images.githubusercontent.com/54281766/73813782-1014f000-4807-11ea-91e8-23eec5567333.png)

2. Also what's with the modal box?
![image](https://user-images.githubusercontent.com/54281766/73813877-62561100-4807-11ea-8d21-62ef90c00ab6.png)

3. Change the `see more` button to a link.

**Comment by rasoolbasha048022** [comment]
i'll fix these issues ...

**Comment by rasoolbasha048022** [comment]
I Fixed the issues.Below is the link

https://kwikui.com/view/7e5dcb#view

**Comment by abhilash-m96** [comment]
* I still don't see the hyper link in place of the button.
* Fix the modal box height to that of the screen and I want it to be scrollable
* Raise a PR once it's done.

**Comment by rasoolbasha048022** [comment]
Fixed the recent issues find it below

https://kwikui.com/view/7e5dcb#view

**Comment by abhilash-m96** [comment]
@rasoolbasha048022  
* I don't see any ways to give `corpus` input.
* I'm getting error for the phrase `egfr kidney`

**Comment by rasoolbasha048022** [comment]
the recent issues are fixed.
Below is the link

https://kwikui.com/view/7e5dcb?phrase=egfr%20&corpus=Core%20Corpus#view

**Comment by abhilash-m96** [comment]
@rasoolbasha048022 I'm not seeing any data for phrase `kidney`.
Even though there is response from backend.

**Comment by rasoolbasha048022** [comment]
I Fixed that issue 
find the link below

https://kwikui.com/view/7e5dcb?phrase=kidneyasdf&corpus=Core%20Corpus#view

**Comment by rasoolbasha048022** [comment]
I'll follow the suggestion that you told
